### ISSUE TITLE
Fix tests on Windows

### ISSUE THREAD

**Issue by sunjay** [sunjay/wolf-asm#3]
The assembler tests added in f76a1d7b3e704e6f772f056128ab1219d8e7ec0a fail [on windows](https://dev.azure.com/sunjayv/wolf-asm/_build/results?buildId=543&view=logs&j=3df22538-2a64-5d6a-ccd1-435dcd87d567&t=bf3eb6bd-922a-54d8-c69d-ad12570afe6e) because the error messages do not match the generated files. I thought this might be something to do with line endings, so I added https://github.com/sunjay/wolf-asm/commit/71ca0c4dcedd2115a98a50c067603cfeb5aaa880, but that did not fix the problem.

I do not have a Windows machine to test this with right now, so any help on this would be appreciated.

**Comment by rrbutani** [comment]
I [started](https://github.com/sunjay/wolf-asm/compare/master...rrbutani:master) trying to fix this and I found a few different things that are causing discrepancies on Windows:
  - There's the return carriage thing but I think it's actually caused by `git`, not the assembler emitting line endings on Windows.
    * I [added a `.gitattributes` file](https://github.com/sunjay/wolf-asm/commit/f36c1e49c688a95323dba7e7728830a051a62196) and added a thing that strips out `\r`s when reading in the `.stderr` files (both the `.stderr` file and the stdout/stderr `\r` stripping are kinda made redundant by this but I left them in anyways since they don't hurt).
    * This seems to fix the errors where the spans don't line up (off by one because of the return carriages that git adds to `.wa` files) for me.
  - There's path separator mismatch. I think `Path` and friends will emit a `/` if you give it a path string that has `/`s in it but for any components that it appends it'll use `\`s so you end up with weird looking paths like `test/ui\foo`.
    * I kinda fixed this in a hacky way by [manually piecing together the paths](https://github.com/sunjay/wolf-asm/commit/929acc00f56436e7ae0ffd04f0615727cd1926e7), but this only covers some of the errors. Any errors produced by the assembler that have paths in them still have this problem.
    * I wasn't sure if you wanted to fix this by having the assembler always use `/` as the path separator in error messages or by having different `.stderr` files for Windows for those tests.
  - The last kind of error are the places where the assembler emits an OS error, like this:
    ```diff
    - "[tests/ui/include-not-found.wa:1:10-1:28] error: unable to read included source file: `tests/ui\\does-not-exist.wa`: The system cannot find the file specified. (os error 2)\n\nerror: aborting due to 1 previous error\n\n"
    + "[tests/ui/include-not-found.wa:1:10-1:28] error: unable to read included source file: `tests/ui/does-not-exist.wa`: No such file or directory (os error 2)\n\nerror: aborting due to 1 previous error\n\n"
    ```
    * Having different `.stderr` files for Windows for these tests seems like the easiest fix.

**Comment by sunjay** [comment]
Thanks for looking into this @rrbutani! I think your assessment is absolutely correct. Your idea to have Windows-specific stderr files would definitely the best solution for this.

Having said that, this isn't a project where I am willing to add the additional maintenance/implementation burden of having to keep and update those additional files. That's why I've opted to just disable Windows tests in CI for the timebeing (https://github.com/sunjay/wolf-asm/commit/a5c00a43df67b47fb85b758784507c50e2994f95). 

Thanks again for your help diagnosing this!
